-- Generated by tools/build_installer.py. Source: src/installer*.lua
-- Installer release: v0.9.9
-- Bootstrap API: 1
local modules = {}
local function require(name) return assert(modules[name]) end
modules["installer_sha256"] = (function()
-- SHA-256 for the installer, implemented from the algorithm in FIPS 180-4.
-- A word is two unsigned 16-bit limbs. No operation needs unsigned 32-bit
-- numbers, floating point, native bit operations, or Lua newer than 5.1.
local M = {}
local byte, char, concat = string.byte, string.char, table.concat
local powers = { [0] = 1 }
for n = 1, 16 do powers[n] = powers[n - 1] * 2 end

-- Small nibble tables keep memory bounded without one operation per bit.
local xt, at = {}, {}
for a = 0, 15 do
    for b = 0, 15 do
        local x, y, v, av, bit = a, b, 0, 0, 1
        for _ = 1, 4 do
            local xb, yb = x % 2, y % 2
            if xb ~= yb then v = v + bit end
            if xb == 1 and yb == 1 then av = av + bit end
            x, y, bit = (x - xb) / 2, (y - yb) / 2, bit * 2
        end
        local p = a * 16 + b + 1
        xt[p], at[p] = v, av
    end
end

local function combine(a, b, lookup)
    local a0, b0 = a % 16, b % 16
    local result = lookup[a0 * 16 + b0 + 1]
    a, b = (a - a0) / 16, (b - b0) / 16
    a0, b0 = a % 16, b % 16
    result = result + lookup[a0 * 16 + b0 + 1] * 16
    a, b = (a - a0) / 16, (b - b0) / 16
    a0, b0 = a % 16, b % 16
    result = result + lookup[a0 * 16 + b0 + 1] * 256
    a, b = (a - a0) / 16, (b - b0) / 16
    return result + lookup[a * 16 + b + 1] * 4096
end

local function xor(a, b) return combine(a, b, xt) end
local function band(a, b) return combine(a, b, at) end

-- Yamaha provides this library from _RT_LUA_VERSION 1.01. Use only positive
-- 16-bit operands, so its unsigned32/BIGNUM rules cannot change our arithmetic.
-- Feature probes also keep this module usable with other Lua implementations.
local native = rawget(_G, "bit")
if type(native) == "table" and type(native.bxor) == "function" and type(native.band) == "function" then
    local ok, valid = pcall(function()
        for _, pair in ipairs({{0, 0}, {65535, 0}, {65535, 65535}, {32768, 32767}, {43690, 21845}, {4660, 22136}}) do
            local a, b = pair[1], pair[2]
            if native.bxor(a, b) ~= xor(a, b) or native.band(a, b) ~= band(a, b) then return false end
        end
        return true
    end)
    if ok and valid then xor, band = native.bxor, native.band end
end

local function rotate(h, l, n)
    if n >= 16 then h, l, n = l, h, n - 16 end
    local p, q = powers[n], powers[16 - n]
    local hr, lr = h % p, l % p
    return (h - hr) / p + lr * q, (l - lr) / p + hr * q
end

local function sigma(h, l, a, b, c, shift)
    local ah, al = rotate(h, l, a)
    local bh, bl = rotate(h, l, b)
    local ch, cl
    if shift then
        local p = powers[c]
        local hr, lr = h % p, l % p
        ch, cl = (h - hr) / p, (l - lr) / p + hr * powers[16 - c]
    else
        ch, cl = rotate(h, l, c)
    end
    return xor(xor(ah, bh), ch), xor(xor(al, bl), cl)
end

local function words(text)
    local high, low = {}, {}
    for word in text:gmatch("%x+") do
        high[#high + 1] = tonumber(word:sub(1, 4), 16)
        low[#low + 1] = tonumber(word:sub(5, 8), 16)
    end
    return high, low
end

local kh, kl = words([[
428a2f98 71374491 b5c0fbcf e9b5dba5 3956c25b 59f111f1 923f82a4 ab1c5ed5
d807aa98 12835b01 243185be 550c7dc3 72be5d74 80deb1fe 9bdc06a7 c19bf174
e49b69c1 efbe4786 0fc19dc6 240ca1cc 2de92c6f 4a7484aa 5cb0a9dc 76f988da
983e5152 a831c66d b00327c8 bf597fc7 c6e00bf3 d5a79147 06ca6351 14292967
27b70a85 2e1b2138 4d2c6dfc 53380d13 650a7354 766a0abb 81c2c92e 92722c85
a2bfe8a1 a81a664b c24b8b70 c76c51a3 d192e819 d6990624 f40e3585 106aa070
19a4c116 1e376c08 2748774c 34b0bcb5 391c0cb3 4ed8aa4a 5b9cca4f 682e6ff3
748f82ee 78a5636f 84c87814 8cc70208 90befffa a4506ceb bef9a3f7 c67178f2
]])

local function pack16(n)
    return char((n - n % 256) / 256, n % 256)
end

function M.hex(data, yield_fn)
    assert(type(data) == "string", "SHA256 input must be a string")
    assert(yield_fn == nil or type(yield_fn) == "function", "invalid SHA256 yield callback")
    local length = #data
    -- Encode length * 8 without ever multiplying a potentially large length.
    local low = length % 8192
    local rest = (length - low) / 8192
    local middle = rest % 65536
    local trailer = pack16(0) .. pack16((rest - middle) / 65536)
        .. pack16(middle) .. pack16(low * 8)
    data = data .. char(128) .. string.rep(char(0), (119 - length % 64) % 64) .. trailer
    local hh, hl = words("6a09e667 bb67ae85 3c6ef372 a54ff53a 510e527f 9b05688c 1f83d9ab 5be0cd19")
    local wh, wl = {}, {}
    local blocks = 0
    for start = 1, #data, 64 do
        for i = 1, 16 do
            local p = start + (i - 1) * 4
            wh[i], wl[i] = byte(data, p) * 256 + byte(data, p + 1),
                byte(data, p + 2) * 256 + byte(data, p + 3)
        end
        for i = 17, 64 do
            local ah, al = sigma(wh[i - 15], wl[i - 15], 7, 18, 3, true)
            local bh, bl = sigma(wh[i - 2], wl[i - 2], 17, 19, 10, true)
            local sum = wl[i - 16] + al + wl[i - 7] + bl
            local remainder = sum % 65536
            wl[i] = remainder
            wh[i] = (wh[i - 16] + ah + wh[i - 7] + bh + (sum - remainder) / 65536) % 65536
        end
        local ah, al, bh, bl, ch, cl, dh, dl = hh[1], hl[1], hh[2], hl[2], hh[3], hl[3], hh[4], hl[4]
        local eh, el, fh, fl, gh, gl, ih, il = hh[5], hl[5], hh[6], hl[6], hh[7], hl[7], hh[8], hl[8]
        for i = 1, 64 do
            local sh, sl = sigma(eh, el, 6, 11, 25)
            -- Ch(e,f,g) = g XOR (e AND (f XOR g)).
            local chooseh = xor(gh, band(eh, xor(fh, gh)))
            local choosel = xor(gl, band(el, xor(fl, gl)))
            local sum = il + sl + choosel + kl[i] + wl[i]
            local t1l = sum % 65536
            local t1h = (ih + sh + chooseh + kh[i] + wh[i] + (sum - t1l) / 65536) % 65536
            sh, sl = sigma(ah, al, 2, 13, 22)
            -- Maj(a,b,c) = (a AND b) XOR ((a XOR b) AND c).
            local majorh = xor(band(ah, bh), band(xor(ah, bh), ch))
            local majorl = xor(band(al, bl), band(xor(al, bl), cl))
            sum = sl + majorl
            local t2l = sum % 65536
            local t2h = (sh + majorh + (sum - t2l) / 65536) % 65536
            ih, il, gh, gl, fh, fl = gh, gl, fh, fl, eh, el
            sum = dl + t1l
            el = sum % 65536
            eh = (dh + t1h + (sum - el) / 65536) % 65536
            dh, dl, ch, cl, bh, bl = ch, cl, bh, bl, ah, al
            sum = t1l + t2l
            al = sum % 65536
            ah = (t1h + t2h + (sum - al) / 65536) % 65536
        end
        local finalh, finall = {ah, bh, ch, dh, eh, fh, gh, ih}, {al, bl, cl, dl, el, fl, gl, il}
        for i = 1, 8 do
            local sum = hl[i] + finall[i]
            hl[i] = sum % 65536
            hh[i] = (hh[i] + finalh[i] + (sum - hl[i]) / 65536) % 65536
        end
        blocks = blocks + 1
        if yield_fn and blocks % 32 == 0 then yield_fn() end
    end
    local result = {}
    for i = 1, 8 do result[i] = string.format("%04x%04x", hh[i], hl[i]) end
    return concat(result)
end

return M

end)()
modules["installer_http"] = (function()
-- HTTPS downloads for the installer. Do not include response headers, URLs,
-- cookies, or native error strings in errors: redirects can contain signatures.
local M = {}
local ALLOWED = {
    ["github.com"] = true,
    ["raw.githubusercontent.com"] = true,
    ["release-assets.githubusercontent.com"] = true,
    ["objects.githubusercontent.com"] = true,
}
local REDIRECT = { [301] = true, [302] = true, [303] = true, [307] = true, [308] = true }

local function fail(message)
    error("Installer HTTP: " .. message, 0)
end

local function validate_url(url)
    if type(url) ~= "string" or #url == 0 then fail("missing URL") end
    if #url > 2048 then fail("URL exceeds the 2048-character firmware limit") end
    if url:find("[%z\1-\32\127]") or url:find("\\", 1, true) or url:find("#", 1, true) then
        fail("URL contains forbidden characters")
    end
    local host, path = url:match("^https://([^/]+)(/.*)$")
    if not host or not ALLOWED[host] then fail("URL must use HTTPS and an allowed GitHub host") end
    -- An exact authority match above also excludes ports and user information.
    local i = 1
    while true do
        local p = url:find("%", i, true)
        if not p then break end
        local hex = url:sub(p + 1, p + 2)
        if #hex ~= 2 or not hex:match("^%x%x$") then fail("URL contains an invalid percent escape") end
        local value = tonumber(hex, 16)
        if value < 32 or value == 127 then fail("URL contains an encoded control character") end
        i = p + 3
    end
    return host, path
end

local function request(rt, url)
    validate_url(url)
    if type(rt) ~= "table" or type(rt.httprequest) ~= "function" then
        fail("rt.httprequest is unavailable; HTTPS-capable firmware is required")
    end
    -- Yamaha may re-encode URL percent signs. Never try to compensate by
    -- decoding signed queries: spaces can also become '+', changing signatures.
    local ok, response = pcall(rt.httprequest, { url = url, method = "GET", timeout = 30 })
    if not ok or type(response) ~= "table" or response.rtn1 ~= true then
        if #url > 255 then
            fail("request failed; URLs above 255 characters require firmware with 2048-character URL support")
        end
        fail("request failed; check HTTPS support and connectivity")
    end
    local code = response.code
    if type(code) ~= "number" or code % 1 ~= 0 or code < 100 or code > 599 then
        fail("response has an invalid HTTP status")
    end
    return response
end

local function location(header)
    if type(header) ~= "string" then fail("redirect has no Location header") end
    local found, previous_location
    for line in (header .. "\n"):gmatch("([^\n]*)\n") do
        if line:sub(-1) == "\r" then line = line:sub(1, -2) end
        if line:find("\r", 1, true) then fail("redirect has malformed headers") end
        if line:match("^[ \t]") then
            if previous_location then fail("redirect has a folded Location header") end
        else
            local name, value = line:match("^([^:]+):(.*)$")
            previous_location = name and name:lower() == "location"
            if previous_location then
                if found then fail("redirect has duplicate Location headers") end
                found = value:match("^[ \t]*(.-)[ \t]*$")
            end
        end
    end
    if not found or found == "" then fail("redirect has no Location header") end
    validate_url(found)
    return found
end

function M.fetch(rt, url, maxbytes)
    if type(maxbytes) ~= "number" or maxbytes < 1 or maxbytes % 1 ~= 0 then
        fail("invalid download size limit")
    end
    local current, seen, redirects = url, {}, 0
    while true do
        validate_url(current)
        if seen[current] then fail("redirect loop") end
        seen[current] = true
        local response = request(rt, current)
        if REDIRECT[response.code] then
            if redirects >= 5 then fail("too many redirects (maximum 5)") end
            current = location(response.header)
            redirects = redirects + 1
        elseif response.code == 200 then
            if type(response.body) ~= "string" then fail("HTTP 200 response has no body") end
            if #response.body > maxbytes then fail("download exceeds its size limit") end
            return response.body, current
        else
            fail("download returned HTTP " .. response.code)
        end
    end
end

return M

end)()
modules["installer"] = (function()
-- Version-pinned installer. Separate from the DNS relay runtime.
local sha = require("installer_sha256")
local http = require("installer_http")
local M = {}
local target = "/lua/rtx-dns.lua"
local self = "/lua/rtx-dns-install.lua"
local stage = "/lua/rtx-dns.install-new"
local backup = "/lua/rtx-dns.install-old"
local marker = "/lua/rtx-dns.install-state"

function M.validate_release(release)
    assert(type(release) == "table", "version-pinned release metadata is required")
    local version, digest, bytes, url = release.version, release.sha256, release.bytes, release.url
    assert(type(version) == "string" and version:match("^v%d+%.%d+%.%d+$"), "invalid pinned version")
    assert(type(digest) == "string" and #digest == 64 and digest:match("^[0-9a-f]+$"), "invalid pinned SHA256")
    assert(type(bytes) == "number" and bytes % 1 == 0 and bytes >= 1024 and bytes <= 524288,
        "invalid pinned file size")
    assert(type(url) == "string", "missing pinned download URL")
    local ref, path_version = url:match("^https://raw%.githubusercontent%.com/Yamar50/rtx%-dns%-tcp%-lua/([0-9a-f]+)/installer/versions/(v%d+%.%d+%.%d+)/rtx%-dns%.lua$")
    assert(ref and #ref == 40 and path_version == version, "download URL must pin the expected version and commit")
    return version, digest, bytes, url
end

function M.schedule(config)
    local used, existing = {}, nil
    for line in config:gmatch("[^\r\n]+") do
        local id = line:match("^schedule at (%d+) ")
        if id then
            used[tonumber(id)] = true
            if line:find("rtx-dns.lua", 1, true) or line:find("nvr-dns.lua", 1, true) then
                assert(line == "schedule at " .. id .. " startup * lua " .. target,
                    "custom DNS startup schedule: update it manually before installing")
                assert(not existing, "multiple DNS startup schedules")
                existing = tonumber(id)
            end
        end
    end
    if existing then return existing, true end
    for id = 1, 999 do if not used[id] then return id, false end end
    error("no free schedule number in installer search range 1..999")
end

function M.count(status, path)
    local paths, commands = 0, 0
    for line in status:gmatch("[^\r\n]+") do
        if line:match(":%s*(/%S+)%s*$") == path then paths = paths + 1 end
        if line:match("%f[%a]lua%s+(/%S+)%s*$") == path then commands = commands + 1 end
    end
    return math.max(paths, commands)
end

function M.installers(status)
    local count = M.count(status, self)
    for line in status:gmatch("[^\r\n]+") do
        if line:find("lua %-e ") and line:find("local DNSINSTALL_BOOT=", 1, true) then count = count + 1 end
    end
    return count
end

local function config_text(raw)
    local lines = {}
    for line in raw:gmatch("[^\r\n]+") do
        if not line:match("^%s*#") and line:match("%S") then lines[#lines + 1] = line end
    end
    return table.concat(lines, "\n")
end

function M.run(rt, mode, env, release)
    env = env or {}
    local fs, system = env.io or io, env.os or os
    local compile, say = env.compile or loadstring or load, env.print or print
    local step = 1
    local function log(s) say("DNSINSTALL (" .. step .. "/9) " .. s) end
    local function progress(number, message)
        step = number
        log(message)
    end
    local function command(cmd)
        local ok, output = rt.command(cmd, "off")
        assert(ok and (output == nil or type(output) == "string"), "router command failed: " .. cmd)
        if cmd:match("^show ") then assert(type(output) == "string", "missing router output: " .. cmd) end
        return output or ""
    end
    local function read(path)
        local f = fs.open(path, "rb")
        if not f then return nil end
        local data = f:read("*a"); local ok = f:close()
        assert(type(data) == "string" and ok, "file read failed: " .. path)
        return data
    end
    local function write(path, data)
        local f = assert(fs.open(path, "wb"), "cannot write: " .. path)
        local ok = f:write(data); local closed = f:close()
        assert(ok and closed and read(path) == data, "file write/read-back failed: " .. path)
    end
    local function remove(path)
        if read(path) ~= nil then assert(system.remove(path), "cannot remove: " .. path) end
    end
    local function status() return command("show status lua running") end
    local function wait_stopped()
        for _ = 1, 10 do
            if M.count(status(), target) == 0 then return end
            rt.sleep(1)
        end
        error("DNS task did not stop")
    end
    local function stop()
        if M.count(status(), target) > 0 then command("terminate lua file " .. target) end
        wait_stopped()
    end
    local function running()
        -- Do not mistake successful submission of an asynchronous lua command
        -- for a running relay. Check its exact path repeatedly after startup.
        rt.sleep(5)
        for _ = 1, 3 do
            assert(M.count(status(), target) == 1, "DNS task failed to stay running; inspect DNSRELAY log")
            rt.sleep(1)
        end
    end
    local old, was_running, changed, added_schedule
    local complete, save_attempted, prepared = false, false, false
    local ok, err = pcall(function()
        progress(1, "Checking installation settings and router status")
        assert(mode == "yes" or mode == "no", "usage: lua " .. self .. " yes|no")
        local version, expected, bytes, url = M.validate_release(release)
        assert(type(rt.sleep) == "function", "rt.sleep is required by the installer")
        assert(not read(marker) and not read(stage) and not read(backup),
            "previous installer files remain; see installer recovery instructions before retrying")
        local tasks = status()
        assert(M.installers(tasks) <= 1, "another installer is running")
        assert(not tasks:find("nvr-dns.lua", 1, true), "stop the NVR trial before installing")
        assert(M.count(tasks, target) <= 1, "multiple DNS tasks are running")
        local config = config_text(command("show config"))
        local schedule_id, existing = M.schedule(config)
        progress(2, "Downloading pinned release: " .. version .. " (version and SHA256 fixed in this installer)")
        local body = http.fetch(rt, url, bytes)
        assert(#body == bytes, "pinned file size mismatch; current DNS unchanged")
        assert(body:byte(1) ~= 27, "invalid Lua source download")
        progress(3, "Checking SHA256 and Lua syntax (please wait)")
        local hash_ticks = 0
        assert(sha.hex(body, function()
            hash_ticks = hash_ticks + 1
            if hash_ticks % 8 == 0 then rt.sleep(1) end
            if hash_ticks % 32 == 0 then log("SHA256 progress: " .. math.min(hash_ticks * 2048, #body) .. "/" .. #body .. " bytes") end
        end) == expected, "SHA256 mismatch; current DNS unchanged")
        assert(compile(body), "downloaded Lua syntax is invalid")
        log("SHA256 OK: " .. expected)
        progress(4, "Preparing verified file and backup")
        assert(config_text(command("show config")) == config, "router config changed during download; retry")
        tasks = status()
        assert(M.installers(tasks) <= 1 and M.count(tasks, target) <= 1, "another installer or DNS task appeared")
        assert(not tasks:find("nvr-dns.lua", 1, true), "NVR trial task appeared during download")
        -- Existing directories may make this command return false. The
        -- preparation writes and read-back below verify that it is usable.
        rt.command("make directory /lua", "off")
        old = read(target)
        was_running = M.count(tasks, target) == 1
        assert(not was_running or old, "running DNS file is missing")
        prepared = true
        if old ~= body then write(stage, body) end
        if old then write(backup, old) end
        write(marker, "version=" .. version .. "\nsha256=" .. expected .. "\nold=" .. (old and "yes" or "no")
            .. "\nrunning=" .. (was_running and "yes" or "no") .. "\n")
        assert(read(target) == old, "installed file changed during preparation")
        assert(config_text(command("show config")) == config, "router config changed during preparation; retry")
        tasks = status()
        assert(M.installers(tasks) <= 1 and M.count(tasks, target) == (was_running and 1 or 0)
            and not tasks:find("nvr-dns.lua", 1, true), "Lua tasks changed during preparation; retry")
        progress(5, "Stopping the current DNS task, if running")
        changed = true
        stop()
        progress(6, "Installing and starting the selected DNS script")
        if old ~= body then
            remove(target)
            assert(system.rename(stage, target), "cannot activate staged Lua file")
        else
            log("installed file matches " .. version .. "; restarting to load verified code and current config")
        end
        assert(read(target) == body, "activated file differs from verified download")
        command("lua " .. target)
        progress(7, "Checking that the DNS task stays running")
        running()
        log("DNS task is running: " .. target)
        assert(config_text(command("show config")) == config, "router config changed during startup")
        progress(8, mode == "yes" and "Configuring autostart and saving current configuration"
            or "Keeping autostart and saved configuration unchanged")
        if mode == "yes" then
            if not existing then
                local line = "schedule at " .. schedule_id .. " startup * lua " .. target
                added_schedule = schedule_id
                command(line)
                local after = command("show config")
                local id, found = M.schedule(after)
                assert(found and id == schedule_id, "startup schedule verification failed")
                local without = {}
                for l in config_text(after):gmatch("[^\n]+") do if l ~= line then without[#without + 1] = l end end
                assert(table.concat(without, "\n") == config, "router config changed while adding startup schedule")
            end
            -- save may affect the boot-selected config rather than CONFIG0.
            -- If its response is lost, keep the verified running file; never
            -- roll it back while a new startup entry may already be durable.
            save_attempted = true
            command("save")
            log("autostart schedule " .. schedule_id .. " configured; current router configuration saved")
        else
            log("autostart configuration unchanged; config not saved")
        end
        complete = true
        progress(9, env.memory_bootstrap and "Removing temporary files" or "Removing temporary files and installer")
        remove(backup); remove(marker); remove(stage)
        if not env.memory_bootstrap then remove(self) end
        log("Installation complete: " .. version .. (env.memory_bootstrap and "." or "; installer removed."))
        log("Press ENTER to display the router command prompt.")
    end)
    if not ok then
        log("failed: " .. tostring(err))
        if (changed or added_schedule) and not complete and not save_attempted then
            local restored, restore_error = pcall(function()
                if added_schedule then
                    local owned = "schedule at " .. added_schedule .. " startup * lua " .. target
                    for line in command("show config"):gmatch("[^\r\n]+") do
                        if line == owned then command("no schedule at " .. added_schedule) end
                    end
                end
                if changed then
                    stop()
                    if old then
                        if read(target) ~= old then write(target, old) end
                    else remove(target) end
                    if was_running then command("lua " .. target); running() end
                end
                if prepared then remove(stage); remove(backup); remove(marker) end
            end)
            if restored then log("previous file and running state restored")
            else log("automatic rollback failed: " .. tostring(restore_error) .. "; keep " .. backup) end
        elseif prepared and not changed then
            local cleaned = pcall(function() remove(stage); remove(backup); remove(marker) end)
            log(cleaned and "current DNS unchanged; staging cleaned" or "current DNS unchanged; staging cleanup failed")
        elseif save_attempted then
            log("verified DNS retained; check whether save succeeded and inspect remaining installer files")
        end
        return nil, tostring(err)
    end
    return true
end
return M

end)()
local release = {version="v0.9.9",sha256="1cd98160aa1b6895556721f8e72d5bd0af68da83aa71fcc41dfa61912fe425ee",bytes=151437,url="https://raw.githubusercontent.com/Yamar50/rtx-dns-tcp-lua/1184a53e481e7ceeea9a8603d5499e62abc33b93/installer/versions/v0.9.9/rtx-dns.lua"}
local mode, expected_version = ...
local env
if expected_version ~= nil then
    assert(expected_version == release.version, "Installer version mismatch")
    env = {memory_bootstrap = true}
else
    mode = mode or (arg and arg[1])
end
local ok, err = modules.installer.run(rt, mode, env, release)
if not ok then error(err, 0) end
