#!/usr/bin/env python3
"""Bundle plain Lua 5.1 modules and one explicit config into a router file."""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    p = argparse.ArgumentParser(description=__doc__)
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument('--config', type=Path)
    mode.add_argument('--test', type=Path)
    p.add_argument('--output', type=Path, required=True)
    a = p.parse_args()
    chunks = ['-- Generated by tools/build.py. Edit source modules, then rebuild.\n',
              'local modules = {}\nlocal function require(name)\n'
              '  assert(modules[name], "module missing: " .. name)\n'
              '  return modules[name]\nend\n']
    for name in ['interfaces', 'dns_wire', 'cache', 'dns_policy', 'dns_runtime', 'auto_config', 'relay', 'main']:
        text = (ROOT / 'src' / (name + '.lua')).read_text()
        chunks.append(f'modules["{name}"] = (function()\n{text}\nend)()\n')
    if a.test:
        chunks.append(a.test.read_text())
    else:
        chunks.append('local config = (function()\n' + a.config.read_text() + '\nend)()\n')
        chunks.append('return modules.main.start(config, rt)\n')
    data = ''.join(chunks).encode('ascii')
    a.output.parent.mkdir(parents=True, exist_ok=True)
    a.output.write_bytes(data)
    print(f'{a.output}: {len(data)} bytes sha256={hashlib.sha256(data).hexdigest()}')


if __name__ == '__main__':
    main()
