#!/usr/bin/env python3
"""Build the standalone DNS relay uninstaller, or print its pinned command."""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
RELATIVE = 'installer/rtx-dns-uninstall.lua'
HEADER = '-- DNS relay uninstaller API: 1\n'


def build(root=ROOT):
    source = (root / 'src/uninstaller.lua').read_text()
    body = (HEADER + '-- Generated by tools/build_uninstaller.py.\n'
            + 'local uninstaller = (function()\n' + source + '\nend)()\n'
            + 'local mode = ...\n'
            + 'assert(mode == nil or mode == "uninstall", "Uninstaller mode mismatch")\n'
            + 'local ok, err = uninstaller.run(rt)\n'
            + 'if not ok then error(err, 0) end\n').encode('ascii')
    path = root / RELATIVE
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(body)
    return body


def command(ref, root=ROOT):
    if not re.fullmatch('[0-9a-f]{40}', ref):
        raise ValueError('ref must be an immutable 40-character commit ID')
    kind = subprocess.run(['git', 'cat-file', '-t', ref], cwd=root, check=True,
                          capture_output=True).stdout.strip()
    if kind != b'commit':
        raise ValueError('ref must identify a commit')
    body = subprocess.run(['git', 'show', f'{ref}:{RELATIVE}'], cwd=root,
                          check=True, capture_output=True).stdout
    if not body.startswith(HEADER.encode('ascii')):
        raise ValueError('unsupported uninstaller API')
    if not 1024 <= len(body) <= 65536:
        raise ValueError('unexpected uninstaller size')
    url = f'https://raw.githubusercontent.com/Yamar50/rtx-dns-tcp-lua/{ref}/{RELATIVE}'
    # Keep this marker compatible with the already-published installer guard.
    source = ('local DNSINSTALL_BOOT="uninstall";'
              f'local r=rt.httprequest({{url="{url}",method="GET",timeout=30}});'
              f'assert(r.rtn1 and r.code==200 and type(r.body)=="string" and #r.body=={len(body)},"Uninstaller download failed");'
              'assert(loadstring(r.body))(DNSINSTALL_BOOT)')
    assert len(source) < 4095 and "'" not in source and '\\' not in source
    return "lua -e '" + source + "'"


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ref', help='print a command for this committed bundle instead of building')
    args = parser.parse_args()
    if args.ref:
        print(command(args.ref))
    else:
        data = build()
        print(f'{RELATIVE}: {len(data)} bytes sha256={hashlib.sha256(data).hexdigest()}')
