#!/usr/bin/env python3
"""Build an installer for one explicitly selected, committed release payload."""
import argparse
from pathlib import Path
import hashlib
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
VERSION = re.compile(r'v[0-9]+\.[0-9]+\.[0-9]+')
REF = re.compile(r'[0-9a-f]{40}')


def release_data(version, payload_ref, root=ROOT):
    if not VERSION.fullmatch(version):
        raise ValueError('an explicit version such as v0.1.4 is required')
    if not REF.fullmatch(payload_ref):
        raise ValueError('payload-ref must be an immutable 40-character commit ID')
    kind = subprocess.run(['git', 'cat-file', '-t', payload_ref], cwd=root,
                          check=True, capture_output=True).stdout.strip()
    if kind != b'commit':
        raise ValueError('payload-ref must identify a commit')
    relative = Path('installer/versions') / version
    files = {}
    for name in ('rtx-dns.lua', 'SHA256SUMS', 'manifest.txt'):
        files[name] = (root / relative / name).read_bytes()
        committed = subprocess.run(['git', 'show', f'{payload_ref}:{relative.as_posix()}/{name}'],
                                   cwd=root, check=True, capture_output=True).stdout
        if files[name] != committed:
            raise ValueError(f'{name} differs from the selected payload commit')
    if files['manifest.txt'] != version.encode('ascii') + b'\n' + files['SHA256SUMS']:
        raise ValueError('manifest version or checksum contents do not match')
    records = []
    for line in files['SHA256SUMS'].decode('ascii').splitlines():
        if not line.strip():
            continue
        match = re.fullmatch(r'([0-9a-fA-F]{64}) [ *](\S+)', line)
        if not match:
            raise ValueError('malformed SHA256SUMS record')
        if match[2] == 'rtx-dns.lua':
            records.append(match[1].lower())
    digest = hashlib.sha256(files['rtx-dns.lua']).hexdigest()
    if len(records) != 1 or records[0] != digest:
        raise ValueError('release payload checksum mismatch or ambiguous checksum')
    size = len(files['rtx-dns.lua'])
    if not 1024 <= size <= 524288:
        raise ValueError('release payload size is outside the supported range')
    return {'version': version, 'sha256': digest, 'bytes': size,
            'url': f'https://raw.githubusercontent.com/Yamar50/rtx-dns-tcp-lua/{payload_ref}/{relative.as_posix()}/rtx-dns.lua'}


def build(version, payload_ref, root=ROOT):
    release = release_data(version, payload_ref, root)
    chunks = ['-- Generated by tools/build_installer.py. Source: src/installer*.lua\n',
              f'-- Installer release: {version}\n',
              '-- Bootstrap API: 1\n',
              'local modules = {}\nlocal function require(name) return assert(modules[name]) end\n']
    for name in ['installer_sha256', 'installer_http', 'installer']:
        chunks.append('modules["' + name + '"] = (function()\n' + (root / 'src' / f'{name}.lua').read_text() + '\nend)()\n')
    chunks.append('local release = {version="%(version)s",sha256="%(sha256)s",bytes=%(bytes)d,url="%(url)s"}\n' % release)
    chunks.append('local mode, expected_version = ...\n'
                  'local env\n'
                  'if expected_version ~= nil then\n'
                  '    assert(expected_version == release.version, "Installer version mismatch")\n'
                  '    env = {memory_bootstrap = true}\n'
                  'else\n'
                  '    mode = mode or (arg and arg[1])\n'
                  'end\n'
                  'local ok, err = modules.installer.run(rt, mode, env, release)\nif not ok then error(err, 0) end\n')
    data = ''.join(chunks).encode('ascii')
    path = root / 'installer/versions' / version / 'rtx-dns-install.lua'
    path.write_bytes(data)
    print(f'{path}: {len(data)} bytes sha256={hashlib.sha256(data).hexdigest()}')
    return data

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--version', required=True)
    parser.add_argument('--payload-ref', required=True)
    args = parser.parse_args()
    build(args.version, args.payload_ref)
