#!/usr/bin/env python3
"""Bundle the independent, Lua 5.1-compatible stable installer."""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[1]

def build():
    chunks = ['-- Generated by tools/build_installer.py. Source: src/installer*.lua\n',
              'local modules = {}\nlocal function require(name) return assert(modules[name]) end\n']
    for name in ['installer_sha256', 'installer_http', 'installer']:
        chunks.append('modules["' + name + '"] = (function()\n' + (ROOT/'src'/f'{name}.lua').read_text() + '\nend)()\n')
    chunks.append('local ok, err = modules.installer.run(rt, arg and arg[1])\nif not ok then error(err, 0) end\n')
    data = ''.join(chunks).encode('ascii')
    path = ROOT/'installer/rtx-dns-install.lua'
    path.parent.mkdir(exist_ok=True)
    path.write_bytes(data)
    print(f'{path}: {len(data)} bytes sha256={hashlib.sha256(data).hexdigest()}')
    return data

if __name__ == '__main__':
    build()
