#!/usr/bin/env python3
"""Generate ASCII Lua byte tables from readable, evidence-based status phrases."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def quoted(raw):
    return '"' + ''.join(chr(b) if 32 <= b < 127 and b not in (34, 92)
                         else '\\%03d' % b for b in raw) + '"'


def render():
    data = json.loads((ROOT / 'tools/status_text.json').read_text())
    sections = {'labels': data['labels'], 'missing': {'true': data['missing']},
                'pp_states': data['pp_states'], 'history': {'true': data['history']}}
    out = ['-- Generated by tools/build_status_text.py; edit tools/status_text.json.\n',
           '-- CP932 is measured on RTX830/RTX1210; UTF-8 preserves input compatibility.\n',
           'return {\n']
    for name, groups in sections.items():
        out.append('  ' + name + ' = {\n')
        seen = {}
        for kind, phrases in groups.items():
            for phrase in phrases:
                for encoding in ('cp932', 'utf-8'):
                    raw = phrase.encode(encoding)
                    if raw in seen:
                        if seen[raw] != kind:
                            raise ValueError('ambiguous status phrase: ' + phrase)
                        continue
                    seen[raw] = kind
                    value = 'true' if kind == 'true' else quoted(kind.encode('ascii'))
                    out.append('    [' + quoted(raw) + '] = ' + value + ',\n')
        out.append('  },\n')
    out.append('}\n')
    return ''.join(out).encode('ascii')


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    path = ROOT / 'src/status_text.lua'
    expected = render()
    if args.check:
        if not path.exists() or path.read_bytes() != expected:
            p.error('status table is stale; run tools/build_status_text.py')
    else:
        path.write_bytes(expected)
    print('status text: ' + ('verified' if args.check else 'generated'))


if __name__ == '__main__':
    main()
