-- DNS relay uninstaller API: 1
-- Generated by tools/build_uninstaller.py.
local uninstaller = (function()
-- Remove only the standard relay installation. No network access or dependencies.
local M = {}
local target = "/lua/rtx-dns.lua"
local self = "/lua/rtx-dns-uninstall.lua"

local function count(status, path)
    local paths, commands = 0, 0
    for line in status:gmatch("[^\r\n]+") do
        if line:match(":%s*(/%S+)%s*$") == path then paths = paths + 1 end
        if line:match("%f[%a]lua%s+(/%S+)%s*$") == path then commands = commands + 1 end
    end
    return math.max(paths, commands)
end

local function normalize(raw)
    local lines = {}
    for line in raw:gmatch("[^\r\n]+") do
        if not line:match("^%s*#") and line:match("%S") then lines[#lines + 1] = line end
    end
    return table.concat(lines, "\n")
end

local function schedules(config)
    local found, keep = {}, {}
    for line in config:gmatch("[^\n]+") do
        local id = line:match("^schedule at (%d+) ")
        if id and (line:find("rtx-dns.lua", 1, true) or line:find("nvr-dns.lua", 1, true)) then
            assert(line == "schedule at " .. id .. " startup * lua " .. target,
                "custom DNS schedule found; no automatic removal")
            found[#found + 1] = { id = id, line = line }
        else keep[#keep + 1] = line end
    end
    return found, table.concat(keep, "\n")
end

function M.run(rt, env)
    env = env or {}
    local fs, system, say = env.io or io, env.os or os, env.print or print
    local step = 0
    local function report(message)
        say("DNSUNINSTALL " .. message)
    end
    local function syslog(message)
        if type(rt.syslog) == "function" then pcall(rt.syslog, "info", ("DNSUNINSTALL " .. message):sub(1, 231)) end
    end
    local function progress(message)
        step = step + 1
        report(string.format("(%d/7) %s", step, message))
    end
    local function command(cmd)
        local ok, output = rt.command(cmd, "off")
        assert(ok and (output == nil or type(output) == "string"), "router command failed: " .. cmd)
        if cmd:match("^show ") then assert(type(output) == "string", "missing router output: " .. cmd) end
        return output or ""
    end
    local function exists(path)
        local file = fs.open(path, "rb")
        if not file then return false end
        assert(file:close(), "cannot close: " .. path)
        return true
    end
    local function guard()
        for _, suffix in ipairs({ "new", "old", "state" }) do
            assert(not exists("/lua/rtx-dns.install-" .. suffix),
                "installer recovery files remain; finish or recover installation first")
        end
        local status = command("show status lua running")
        local active = count(status, "/lua/rtx-dns-install.lua") + count(status, self)
        for line in status:gmatch("[^\r\n]+") do
            -- Retains compatibility with already-published installer guards.
            if line:find("lua %-e ") and line:find("local DNSINSTALL_BOOT=", 1, true) then active = active + 1 end
        end
        assert(active <= 1, "another installer or uninstaller is running")
        assert(not status:find("nvr-dns.lua", 1, true), "NVR trial is running; no automatic removal")
        return count(status, target)
    end
    local function config() return normalize(command("show config")) end
    local ok, err = pcall(function()
        assert(type(rt.sleep) == "function", "rt.sleep is required")
        rt.sleep(1)
        say("")
        progress("Checking router status and the standard installation")
        guard()
        local before = config()
        local entries, after = schedules(before)
        assert(config() == before, "router configuration changed; retry")
        local running = guard()
        progress("Stopping the DNS task, if running")
        if running > 0 then command("terminate lua file " .. target) end
        local stopped = false
        for _ = 1, 10 do
            if guard() == 0 then stopped = true; break end
            rt.sleep(1)
        end
        assert(stopped, "DNS task did not stop; script retained")
        assert(config() == before, "router configuration changed; script retained")
        progress("Removing only the standard DNS startup schedules")
        local expected = before
        for _, entry in ipairs(entries) do
            assert(config() == expected, "router configuration changed; script retained")
            command("no schedule at " .. entry.id)
            local lines = {}
            for line in expected:gmatch("[^\n]+") do if line ~= entry.line then lines[#lines + 1] = line end end
            expected = table.concat(lines, "\n")
            assert(config() == expected, "schedule removal verification failed; script retained")
        end
        assert(expected == after and config() == after, "configuration verification failed; script retained")
        assert(guard() == 0, "DNS task restarted; script retained")
        progress("Saving current router configuration")
        -- Save before deleting the body. A failed or uncertain save leaves a
        -- usable file for a possibly still-persistent startup schedule.
        command("save")
        assert(config() == after, "configuration changed during save; script retained")
        assert(guard() == 0, "DNS task restarted during save; script retained")
        progress("Removing /lua/rtx-dns.lua, if present")
        if exists(target) then assert(system.remove(target), "cannot remove DNS script; retry") end
        progress("Verifying removal")
        assert(not exists(target), "DNS script still exists")
        assert(guard() == 0, "DNS task is still running")
        local remaining = schedules(config())
        assert(#remaining == 0, "DNS startup schedule is still present")
        progress("Uninstallation complete: /lua/rtx-dns.lua removed.")
        syslog("complete: /lua/rtx-dns.lua removed; startup schedules removed and configuration saved")
        report("CLI: press ENTER to display the router command prompt. WebGUI: check Lua history or the system log.")
    end)
    if not ok then
        local message = "failed: " .. tostring(err)
        report(message)
        syslog(message)
        return nil, tostring(err)
    end
    return true
end
return M

end)()
local mode = ...
assert(mode == nil or mode == "uninstall", "Uninstaller mode mismatch")
local ok, err = uninstaller.run(rt)
if not ok then error(err, 0) end
